baseURL = 'https://zijian.li'
title = 'Zero'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zijian Li'

    [languages.en.params]
      author = "Zijian Li"
      description = "Ph.D Student in [Beijing Institute of Technology](https://www.bit.edu.cn). Focusing on Intelligent Unmanned Systems Technology."
      motto = "Most things in the world are not that important. But truth and love matter."
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Honors and Awards'
      url = '#honors-and-awards'
      weight = 4
    [[languages.en.menu.main]]
      name = 'Educations'
      url = '#educations'
      weight = 5
    [[languages.en.menu.main]]
      name = 'Invited Talks'
      url = '#invited-talks'
      weight = 6
    [[languages.en.menu.main]]
      name = 'Internships'
      url = '#internships'
      weight = 7
      
  [languages.zh]
    languageName = '中文'
    weight = 2
    title = '学术主页'
    
    [languages.zh.params]
      author = "李梓建"
      description = "北京理工大学博士生，专注于智能无人系统技术"
      motto = "世界上大部分事，都没有太大意义。真理与爱除外。"
    
    [[languages.zh.menu.main]]
      name = '关于我'
      url = '#about-me'
      weight = 1
    [[languages.zh.menu.main]]
      name = '新闻'
      url = '#news'
      weight = 2
    [[languages.zh.menu.main]]
      name = '发表论文'
      url = '#publications'
      weight = 3
    [[languages.zh.menu.main]]
      name = '荣誉与奖项'
      url = '#honors-and-awards'
      weight = 4
    [[languages.zh.menu.main]]
      name = '教育背景'
      url = '#educations'
      weight = 5
    [[languages.zh.menu.main]]
      name = '受邀报告'
      url = '#invited-talks'
      weight = 6
    [[languages.zh.menu.main]]
      name = '实习经历'
      url = '#internships'
      weight = 7

[params]
  profilePicture = "images/profile.png"
  enableDarkMode = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/"
    icon = "fab fa-github"
  [[params.social]]
    name = "google-scholar"
    url = "https://scholar.google.com/"
    icon = "fab fa-google-scholar"
  [[params.social]]
    name = "email"
    url = "mailto:Frithia@outlook.com"
    icon = "fas fa-envelope"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/"
    icon = "fab fa-linkedin"
  [[params.social]]
    name = "zhihu"
    url = "https://zhihu.com/"
    icon = "fab fa-zhihu"

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
